# Voraussetzunh ...
Get-NavContainerSharedFolders BCDEVSERVER | Format-List
Export-NavContainerObjects BC365csidedev -objectsfolder C:\ProgramData\NavContainerHelper\Extensions\BC365csidedev\my -filter 'type=page;id=21' -exportTo 'fob file'
#Import-ObjectsToNavContainer ...